### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by apjanke** [roslovets/Live-Script-to-Markdown-Converter#1]
Hi! Thanks for sharing this code.

Would you mind adding a license file to indicate how this code is licensed and how it can be used? Maybe you'd be willing to license it under BSD 3-Clause, so it could be posted on MathWorks File Exchange and easily combined with other open source Matlab code?

**Comment by roslovets** [comment]
Added MIT license, thanks.

BTW toolbox is already posted on File Exchange https://www.mathworks.com/matlabcentral/fileexchange/89516

**Comment by apjanke** [comment]
Yay, thanks!
